### ISSUE TITLE
【Review Test Submission: Operating System Support  】Question 3

### ISSUE THREAD

**Issue by MerlinLee** [chuaan/pre_exam#1]
楼主，我想咨询一道题：
Which one of the following is most likely not a well known thread model?

这道题的答案是不是来源于《L3-Threads》P45里介绍的，四个Architectures?

谢谢楼主。

**Comment by chuaan** [comment]
是的 还有一个 是 thread-pool

**Comment by MerlinLee** [comment]
嗯嗯，谢楼主！
